# Generated by Django 4.1.7 on 2023-03-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0002_rename_userpreferences_userpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='currency',
            field=models.CharField(default='Nigerian Naira', max_length=255),
        ),
    ]
